version: '3.7'

services:
  postgres:
      container_name: postgres
      image: postgres:16.2
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: store_db
      ports:
        - "5432:5432"
      volumes:
        - ../docs/sql/store_db.sql:/docker-entrypoint-initdb.d/init.sql
      command: postgres -c 'max_connections=1000'